### ISSUE TITLE
Create a Pod (or other backend resource?) to add links and their metadata, and pull them from

### ISSUE THREAD

**Issue by YetAnotherJonWilson** [solid-contrib/getting-started#2]
It will be faster if NextJS (the framework we're using) can grab all the links at build time, and not at runtime, so that when the page renders, it's not waiting to make a call to the Pod (or other resource).
So, some questions that need to be answered for this issue:
1) We'll start by assuming that we're going to use a Pod for this purpose, but is there a reason to use a different resource instead?
2) If we store the links to documentation in a Pod, do we need to use (or should we use) an existing ontology? Is there one for something like this?
3) How do we implement NextJS grabbing resources at build time, so we can speed up the frontend?

**Comment by timea-solid** [comment]
1. Sometimes the solidcommunity server gets slow. I propose a trial and error here. See if it is enough for the user experience. 
2. I do not know of any yet. This is a point I can look into or create one for us.
3. This I don't know. Maybe it is not necessary.

**Comment by timea-solid** [comment]
On point 1. to not get stuck, I propose we collect links here in an md file first.

**Comment by YetAnotherJonWilson** [comment]
I'm closing this issue because I have a pod created at https://onboarding.solidcommunity.net/

Also, regarding the second and third questions:
2. I've begun creating the list of links using Penny, which handles the task of creating an ontology as a by-product of adding properties to an item. 
(I'm assuming that my understanding of the way the word "ontology" is used in this context is correct. My understanding is that it refers to the set of URI's that define the subjects, predicates and objects that describe a thing. For example, if I say a "link has url example.com", then the ontology consists of the URI's defining the types of "link", "has url" and "example.com".) 
Anyway, if the above assumption is correct, then Penny handles this because it requires that you choose an existing URI for each subject, object and predicate of each thing you add to a description.
3. Using Nextjs's "getStaticProps" method will solve the problem of potentially slow pod response time, because it makes  requests at build time, not at run time. There is a small trade-off: users won't see any links that have been added to the pod since the last build. However, if we just run the build regularly (it runs automatically on every git push, but we could manually run it more often, or maybe create an automated job to run it frequently), it will make a request to the pod, retrieve the results, populate the pages using the response, and serve the info statically (without making requests to the pod on each http request).
